services:
  - type: web
    name: msl-league
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: MONGODB_URI
        fromGroup: msl
      - key: MONGODB_DB_NAME
        fromGroup: msl
      - key: ADMIN_JWT_SECRET
        fromGroup: msl
      - key: ADMIN_SEED_USERNAME
        fromGroup: msl
      - key: ADMIN_SEED_PASSWORD
        fromGroup: msl
      - key: GRIDFS_BUCKET_NAME
        fromGroup: msl

